jobs:
  danger:
    machine: true
    steps:
      - checkout
      - run:
          command: gem install bundler -v 1.17.1
          name: gem install bundler -v 1.17.1
      - run:
          command: bundle install
          name: bundle install
      - run:
          command: DISABLE_DANGER_SUGGESTER=1 bundle exec danger
          name: danger
          when: always
      - run:
          command: bundle exec rubocop --auto-correct
          name: rubocop
          when: always
      - run:
          command: DISABLE_DANGER_RUBOCOP=1 bundle exec danger
          name: danger
          when: always
  rspec:
    machine: true
    steps:
      - checkout
      - run:
          command: gem install bundler -v 1.17.1
          name: gem install bundler -v 1.17.1
      - run:
          command: bundle install
          name: bundle install
      - run:
          command: bundle exec rspec
          name: rspec
version: 2
workflows:
  version: 2
  test:
    jobs:
      - danger
      - rspec
